#!/usr/bin/env node
// Regenerates the traces the visualizer ships with and checks the JS port.
//
//   cargo build --release && node web/build-traces.js
//
// For every file in samples/ this runs the real binary
// (`zippy stats <file> --trace -`), stores the JSON in web/traces/, bundles
// them into web/traces.js (so index.html works from file:// with no server),
// then runs web/huffman.js on the same bytes and fails loudly if its merges,
// codes, bit stream or stats differ from the Rust output in any way.
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const ZippyJS = require('./huffman.js');

const repo = path.resolve(__dirname, '..');
const exe = path.join(repo, 'target', 'release', process.platform === 'win32' ? 'zippy.exe' : 'zippy');
if (!fs.existsSync(exe)) {
  console.error(`missing ${exe}; run \`cargo build --release\` first`);
  process.exit(1);
}

const order = ['text.txt', 'abracadabra.txt', 'pangram.txt', 'prose.txt', 'source.rs.txt'];
const files = fs.readdirSync(path.join(repo, 'samples'))
  .sort((a, b) => (order.indexOf(a) + 1 || 99) - (order.indexOf(b) + 1 || 99));

fs.mkdirSync(path.join(__dirname, 'traces'), { recursive: true });
const bundle = [];
let failures = 0;

for (const f of files) {
  const rel = `samples/${f}`;
  const json = execFileSync(exe, ['stats', rel, '--trace', '-'], { cwd: repo, encoding: 'utf8' });
  const rust = JSON.parse(json);
  const key = f.replace(/\.txt$/, '').replace(/[^a-z0-9]+/gi, '-');
  fs.writeFileSync(path.join(__dirname, 'traces', `${key}.json`), json);
  bundle.push({ key, file: rel, trace: rust });

  const js = ZippyJS.trace(fs.readFileSync(path.join(repo, rel)), rel);
  const checks = {
    frequencies: [rust.frequencies, js.frequencies],
    merges: [rust.merges, js.merges],
    root: [rust.root, js.root],
    codes: [rust.codes, js.codes],
    bitstream: [rust.bitstream, js.bitstream],
    'stats (integers)': [
      ['original_bytes', 'header_bytes', 'payload_bits', 'payload_bytes', 'compressed_bytes', 'max_code_len'].map(k => rust.stats[k]),
      ['original_bytes', 'header_bytes', 'payload_bits', 'payload_bytes', 'compressed_bytes', 'max_code_len'].map(k => js.stats[k]),
    ],
    // Rust prints floats with 6 decimals, so compare to that precision.
    'stats (floats)': [
      ['ratio', 'entropy_bits', 'avg_code_len'].map(k => Math.abs(rust.stats[k] - js.stats[k]) < 1e-6),
      [true, true, true],
    ],
  };
  const bad = Object.entries(checks).filter(([, [a, b]]) => JSON.stringify(a) !== JSON.stringify(b)).map(([k]) => k);
  if (bad.length) { failures++; console.log(`FAIL ${rel}: JS port differs in ${bad.join(', ')}`); }
  else console.log(`ok   ${rel}: ${rust.codes.length} codes, ${rust.merges.length} merges, ${rust.stats.payload_bits} bits identical in Rust and JS`);
}

fs.writeFileSync(path.join(__dirname, 'traces.js'),
  '// Generated by web/build-traces.js from `zippy stats <sample> --trace -`. Do not edit.\n' +
  `window.ZIPPY_TRACES = ${JSON.stringify(bundle)};\n`);
console.log(`wrote web/traces.js (${bundle.length} traces)`);
process.exit(failures ? 1 : 0);
